/**
 * data/gallery.json -> assets/gallery-data.js
 *
 * The pages read the manifest from a plain <script> global rather than
 * fetch()ing the JSON, so opening index.html straight off disk (file://)
 * still works — CORS blocks fetch for local files.
 *
 *   node tools/build-data.mjs
 */
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const items = JSON.parse(await readFile(path.join(ROOT, 'data/gallery.json'), 'utf8'));

// Strip build-only fields; the browser only needs display data.
const slim = items.map(({ id, title, note, cat, hero, prepHero, chefHero, wide }) => ({
  id, title, note, cat,
  ...(hero && { hero }),
  ...(prepHero && { prepHero }),
  ...(chefHero && { chefHero }),
  ...(wide && { wide }),
}));

await writeFile(
  path.join(ROOT, 'assets/gallery-data.js'),
  '/* GENERATED by tools/build-data.mjs — edit data/gallery.json instead. */\n' +
    'window.GALLERY = ' + JSON.stringify(slim, null, 2) + ';\n'
);
console.log(`gallery-data.js — ${slim.length} items`);
